### ISSUE TITLE
VFP6

### ISSUE THREAD

**Issue by danieltuyub** [ircsasw/VFPconGit#1]
Intenté utilizar la herramienta con proyectos de VFP 6 pero me marcó varios errores, entre ellos errores de sintaxis. Debe ser compatible esta herramienta con VFP 6? O, estoy ejecutando mal la llamada a genxml.app? Gracias de antemano.

**Comment by ircsasw** [comment]
Te recomiendo usar:

[foxbin2prg](https://github.com/fdbozzo/foxbin2prg)
